spring.application.name=ilkwangTech

spring.config.import=application-db.properties

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=100MB

spring.output.ansi.enabled=always

file.uploadBaseLocation=C:/upload
file.chatFileLocation=/messenger/files

server.servlet.session.persistent=false
