spring.application.name=ilkwangTech

spring.config.import=application-db.properties

# 1. 단일 파일의 최대 크기 (예: 50MB)
spring.servlet.multipart.max-file-size=50MB

# 2. 한 요청당 전체 파일 크기의 합 (예: 100MB)
spring.servlet.multipart.max-request-size=100MB


