spring.application.name=ilkwangTech

spring.config.import=application-db.properties

spring.servlet.multipart.max-file-size=50MB

spring.servlet.multipart.max-request-size=100MB

spring.output.ansi.enabled=always

file.chatFileLocation=/messenger/files

server.servlet.session.persistent=false

file.uploadBaseLocation=/usr/local/tomcat/upload/

file.profileImgLocation=/images/profileImg