CREATE TABLE Companys (
                           Company_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name        VARCHAR2(100) NOT NULL,
                           email       VARCHAR2(100),
                           phone       VARCHAR2(20),
                           valid       NUMBER(1) DEFAULT 1,
                           manager     VARCHAR2(100),
                           category    NUMBER(1) DEFAULT 2
);