CREATE TABLE customers (
       customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       name        VARCHAR2(100) NOT NULL,
       email       VARCHAR2(100),
       phone       VARCHAR2(20),
       valid       NUMBER(1) DEFAULT 1
);