-- =================================================================================
-- Sales 패키지용 시퀀스 생성 스크립트
-- =================================================================================
-- Oracle에서 실행하여 sales 엔티티들이 필요로 하는 시퀀스들을 생성합니다.

-- 이미 존재하는 경우 삭제 (선택사항)
-- DROP SEQUENCE CUSTOMERS_SEQ;
-- DROP SEQUENCE DELIVERY_ORDERS_SEQ;
-- DROP SEQUENCE INVOICES_SEQ;
-- DROP SEQUENCE QUOTATIONS_SEQ;
-- DROP SEQUENCE QUOTATION_DETAILS_SEQ;
-- DROP SEQUENCE WAREHOUSES_SEQ;
-- DROP SEQUENCE ITEMSTOCKS_SEQ;
-- DROP SEQUENCE SALES_ORDERS_SEQ;
-- DROP SEQUENCE WAREHOUSE_TRANSACTIONS_SEQ;
-- DROP SEQUENCE PRODUCT_PRICE_HISTORY_SEQ;

-- Sales 패키지용 시퀀스 생성
CREATE SEQUENCE CUSTOMERS_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE DELIVERY_ORDERS_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE INVOICES_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE QUOTATIONS_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE QUOTATION_DETAILS_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE WAREHOUSES_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE ITEMSTOCKS_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE SALES_ORDERS_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE WAREHOUSE_TRANSACTIONS_SEQ START WITH 1001 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_PRICE_HISTORY_SEQ START WITH 1001 INCREMENT BY 1;

-- 확인용 쿼리
SELECT sequence_name, last_number FROM user_sequences WHERE sequence_name IN (
    'CUSTOMERS_SEQ', 'DELIVERY_ORDERS_SEQ', 'INVOICES_SEQ', 
    'QUOTATIONS_SEQ', 'QUOTATION_DETAILS_SEQ', 'WAREHOUSES_SEQ', 
    'ITEMSTOCKS_SEQ', 'SALES_ORDERS_SEQ', 'WAREHOUSE_TRANSACTIONS_SEQ', 'PRODUCT_PRICE_HISTORY_SEQ'
);
