drop table BOM;
drop table operation;
drop table order_item;
drop table sales_order;
drop table item;
drop table company;

CREATE TABLE Item (
                      item_id NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                      item_code VARCHAR2(50) NOT NULL UNIQUE,
                      item_name VARCHAR2(255) NOT NULL,
                      item_type INTEGER,
                      UOM VARCHAR2(10),
                      standard_price NUMBER(15) -- 기준단가
);

CREATE TABLE Company (
                         company_id NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                         company_code VARCHAR2(50) NOT NULL UNIQUE,
                         company_name VARCHAR2(50) NOT NULL,
                         company_type INTEGER,
                         CEO_name VARCHAR2(50),
                         TEL_NO VARCHAR2(20)
);

CREATE TABLE Operation (
                           operation_id NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                           operation_name VARCHAR2(50) NOT NULL,
                           work_center_id NUMBER(19) REFERENCES Equipment(id)
);

CREATE TABLE BOM (
                     bom_id NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                     parent_item_id NUMBER(19) NOT NULL REFERENCES Item(item_id),
                     child_item_id NUMBER(19) NOT NULL REFERENCES Item(item_id),
                     operation_id NUMBER(19) REFERENCES Operation(operation_id),
                     require_qty NUMBER(10,2) NOT NULL -- 재소 품목 소요량
);

CREATE TABLE sales_order (
                             sales_order_id NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                             company_id NUMBER(19) NOT NULL REFERENCES Company(company_id),
                             order_date DATE DEFAULT SYSDATE,
                             expected_delivery_date DATE,
                             order_status VARCHAR2(20) DEFAULT 'PENDING' -- 필수: 주문 상태
);

CREATE TABLE order_item (
                            order_item_id NUMBER(19) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                            sales_order_id NUMBER(19) NOT NULL REFERENCES sales_order(sales_order_id),
                            item_id NUMBER(19) NOT NULL REFERENCES Item(item_id),
                            quantity NUMBER(10) NOT NULL,
                            unit_price NUMBER(19) NOT NULL
);

INSERT INTO Item (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('SAM-001', '삼성 미니 건조기 DV90TA040WH(화이트)', 3, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('SAM-002', '삼성 미니 건조기 DV90TA041DK(다크 그레이)', 3, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('SAM-003', '삼성 미니 건조기 DV90TA042KE(체리 레드)', 3, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('SAM-004', '삼성 AI 건조기 대용량  DV21DG8601GW(그랜드 화이트)', 3, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('SAM-005', '삼성 AI 건조기 대용량  DV21DG8602SB(스페이스 블랙)', 3, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('SAM-006', '삼성 AI 건조기 대용량  DV21DG8603SS(사일런트 실버)', 3, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('SAM-007', '삼성 AI 그랑데 데코레이션스페셜  DV19DK9088CH(샴페인)', 3, 'EA');


-- 프레스용 코일

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-001', 'Hot Rolled Coil', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-002', 'Cold Rolled Coil', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-003', 'Galvanized Coil', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-004', 'Colored Coil', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-005', 'Stainless Steel Coil', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-006', 'Aluminum Coil', 1, 'KG');


-- 분체 도장 도료

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-007', 'WHITE - HYDRID', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-008', 'DARK GRAY - HYDRID', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-009', 'CHERRY RED - HYDRID', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-010', 'GRAND WHITE - HYDRID', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-011', 'SPACE BLACK - HYDRID', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-012', 'SILVER - HYDRID', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-013', 'CHAMPANGE - HYDRID', 1, 'KG');


-- 레진

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-014', 'RESIN - WHITE', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-015', 'RESIN - DARK GRAY', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-016', 'RESIN - CHERRY RED', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-017', 'RESIN - GRAND WHITE', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-018', 'RESIN - SPACE BALCK', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-019', 'RESIN - SILVER', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-020', 'RESIN - CHAMPAGNE', 1, 'KG');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-021', 'RESIN - WHITE', 1, 'KG');

-- PRESS

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-001', 'SAMSUNG-MINI FRONT', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-002', 'SAMSUNG-MINI BACK', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-003', 'SAMSUNG-MINI TOP COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-004', 'SAMSUNG-MINI LEFT COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-005', 'SAMSUNG-MINI RIGHT COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-006', 'SAMSUNG-MINI BOTTOM COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-007', 'SAMSUNG-MINI BACKET WRAPPER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-008', 'SAMSUNG-MINI BACKET BOWL', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-009', 'SAMSUNG-GRANDE FRONT', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-010', 'SAMSUNG-GRANDE BACK', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-011', 'SAMSUNG-GRANDE TOP COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-012', 'SAMSUNG-GRANDE LEFT COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-013', 'SAMSUNG-GRANDE RIGHT COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-014', 'SAMSUNG-GRANDE BOTTOM COVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-015', 'SAMSUNG-GRANDE BACKET WRAPPER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('ST-016', 'SAMSUNG-GRANDE BACKET BOWL', 2, 'EA');


-- 사출 제품 (SAMSUNG - MINI)

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-001', 'SAMSUNG-MINI DOOR-FRONT WHITE', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-002', 'SAMSUNG-MINI DOOR-FRONT DARK-GRAY', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-003', 'SAMSUNG-MINI DOOR-FRONT CHERRY-RED', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-004', 'SAMSUNG-MINI DOOR-BACK WHITE', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-005', 'SAMSUNG-MINI DOOR-BACK DARK-GRAY', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-006', 'SAMSUNG-MINI DOOR-BACK CHERRY-RED', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-007', 'SAMSUNG-MINI DUST-TRAY WHITE', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-008', 'SAMSUNG-MINI DUST-TRAY DARK-GRAY', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-009', 'SAMSUNG-MINI DUST-TRAY CHERRY-RED', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-010', 'SAMSUNG-MINI DETERGENT BOX WHITE', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-011', 'SAMSUNG-MINI DETERGENT BOX DARK-GRAY', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-012', 'SAMSUNG-MINI DETERGENT BOX CHERRY-RED', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-013', 'SAMSUNG-MINI BALANCE TOP', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-014', 'SAMSUNG-MINI BALANCE BOTTOM', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-015', 'SAMSUNG-MINI STEAM FAN', 2, 'EA');

-- 사출제품 삼성 그랑데

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-016', 'SAMSUNG-GRANDE DOOR-FRONT GRANDE-WHITE ', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-017', 'SAMSUNG-GRANDE DOOR-FRONT SPACE-BACK', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-018', 'SAMSUNG-GRANDE DOOR-FRONT SILVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-019', 'SAMSUNG-GRANDE DOOR-FRONT CHAMPAGNE', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-020', 'SAMSUNG-GRANDE DOOR-BACK GRANDE-WHITE ', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-021', 'SAMSUNG-GRANDE DOOR-BACK SPACE-BACK', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-022', 'SAMSUNG-GRANDE DOOR-BACK SILVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-023', 'SAMSUNG-GRANDE DOOR-BACK CHAMPAGNE', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-024', 'SAMSUNG-GRANDE DUST-TRAY GRANDE-WHITE ', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-025', 'SAMSUNG-GRANDE DUST-TRAY SPACE-BACK', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-026', 'SAMSUNG-GRANDE DUST-TRAY SILVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-027', 'SAMSUNG-GRANDE DUST-TRAY CHAMPAGNE', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-028', 'SAMSUNG-GRANDE DETERGENT BOX GRANDE-WHITE ', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-029', 'SAMSUNG-GRANDE DETERGENT BOX SPACE-BACK', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-030', 'SAMSUNG-GRANDE DETERGENT BOX SILVER', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-031', 'SAMSUNG-GRANDE DETERGENT BOX CHAMPAGNE', 2, 'EA');


INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-032', 'SAMSUNG-GRANDE BALANCE TOP', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-033', 'SAMSUNG-GRANDE BALANCE BOTTOM', 2, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('IN-034', 'SAMSUNG-GRANDE STEAM FAN', 2, 'EA');


-- 힌지, 볼트, 패킹, 기판

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-501', 'hinge-door', 1, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-502', 'bolt', 1, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-503', 'packing', 1, 'EA');

INSERT INTO ITEM (ITEM_CODE, ITEM_NAME, ITEM_TYPE, UOM)
VALUES ('RW-504', 'board', 1, 'EA');

select * from item;